# Site settings
title: Introduction to Programming
email: rrockers@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Class notes, stuff from whiteboards, and braindumps I needed to put somewhere.
baseurl: "/pt1420" # the subpath of your site, e.g. /blog/
url: "http://brockers.github.io" # the base hostname & protocol for your site
twitter_username: rrockers
github_username:  brockers
permalink: none
